[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cipherchat = "11111111111111111111111111111111"

[programs.devnet]
cipherchat = "11111111111111111111111111111111"

[programs.testnet]
cipherchat = "11111111111111111111111111111111"

[programs.mainnet]
cipherchat = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
